# Generated by Django 6.0.7 on 2026-07-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان')),
                ('privory', models.IntegerField(default=1, verbose_name='اولویت')),
                ('is_done', models.BooleanField(default=False, verbose_name='آیا انجام شده است؟')),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
