# Generated by Django 6.0.7 on 2026-07-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوا'),
        ),
    ]
